### ISSUE TITLE
Timeout / Throttling issues

### ISSUE THREAD

**Issue by Dayjo** [pat310/google-trends-api#100]
Hello again :)

This isn't really an issue with the library but recently (in the last few days), I noticed that the API requests are taking a lot longer than they used to. Sometimes taking as long as 20 something seconds. 

I'm curious if it's something with my set up (which hasn't changed in about a year), or if anyone else is getting the same problem. I didn't know if Google have implemented any sort of throttling or anything. My solution has just been to increase the timeout of my scripts.

Hopefully,  this is just a temporary issue with Google's service.

**Comment by pat310** [comment]
Still having issues @Dayjo ?

**Comment by pat310** [comment]
Closing for now, reopen if it continues!
