### ISSUE TITLE
Get trends by day

### ISSUE THREAD

**Issue by tagazok** [pat310/google-trends-api#101]
When I choose a large time frame, I get the data per week or month and if I get a small time frame, I get the data per day. Is it possible to get the data of every days on a large time frame?

**Comment by pat310** [comment]
Unfortunately that’s how the google endpoint works. What you could do is just loop over the smaller time frame and join the data together.

**Comment by pat310** [comment]
Were you able to get it working @tagazok ?

**Comment by pat310** [comment]
Closing for now but feel free to reopen or contact me if you can't get it figured out!
