### ISSUE TITLE
Not able to get data for most recent 2 days

### ISSUE THREAD

**Issue by CallMeCreadev** [pat310/google-trends-api#103]
When I run the trends for the last 5 days instead of getting days (n-5:n) i get (n-5:n-2). In other words I am not getting the most recent 2 days of trend data, does anyone else have this problem?

googleTrends.interestOverTime({keyword: 'Valentines Day', startTime: new Date(Date.now() - (5*24 * 60 * 60 * 1000))}, function(err, results) {
  if (err) console.log('oh no error!', err);
  else console.log(results);
});

Returns 3 days of data (april 25th to 27th)

**Comment by joddes** [comment]
Hi how did you solved this? Have the same problem..:)

**Comment by pat310** [comment]
@joddes were you able to figure it out? If you check examples.js there is one in there that you might find helpful. For example, this should return results for the last two days:
```
googleTrends.interestOverTime({
  keyword: 'Valentines Day',
  startTime: new Date(Date.now() - (2 * 24 * 60 * 60 * 1000)),
  granularTimeResolution: true,
}, function(err, results) {
  if (err) console.log('oh no error!', err);
  else console.log(results);
});
```

**Comment by jsappme** [comment]
any solution how to get the last two days of google trends data?

this issue should be reopened

**Comment by shahreahang** [comment]
Its not working for me too !
I've tested PHP api and those are not working too !

**Comment by ajporrasm** [comment]
@pat310 the example code doesn't work for me and I have working code for several weeks now when using longer time spans

Do you have a working example of that example code?

**Comment by ajporrasm** [comment]
this comment did the trick, thanks pat

https://github.com/pat310/google-trends-api/issues/103#issuecomment-443529252
