### ISSUE TITLE
Limit reached and ` too many requests` problem.

### ISSUE THREAD

**Issue by nkint** [pat310/google-trends-api#105]
Hi,
I'm keeping reaching ` too many requests` after some test.
Is there a documentation about limitations?
How many request can I do?

**Comment by pat310** [comment]
Hi @nkint! Google does have a request limit which; unfortunately, I don't have numbers for. People have used [proxy servers](https://github.com/pat310/google-trends-api#proxy-server) to distribute their requests over [multiple IP's](https://github.com/pat310/google-trends-api/pull/80#issuecomment-334737566) with success.

I tried implementing a login functionality similar to [pytrends](https://github.com/GeneralMills/pytrends) but I found that it did not make a difference with the allowable number of requests and I got scared about having people pass their google passwords in 😨so I abandoned that pursuit. One thing I have been thinking about but haven't had the time to try yet is to use something like [puppeteer](https://github.com/GoogleChrome/puppeteer) ¯\_(ツ)_/¯

**Comment by nautonk** [comment]
i get this problem too, i try to change user-agent but it seem like it does not work. Btw it works good if i use aria2c (limit not reached).

Thank you so much, very good repo :)

**Comment by splatcollision** [comment]
Also getting this problem. 

Following up on a related issue in a python trends library, does it make sense to try and detect the statusCode === 429 and presence of a 'set-cookie' header, and automatically resending the request with the correct cookie?

https://github.com/GeneralMills/pytrends/issues/243#issuecomment-392778958 For reference...

**Comment by pat310** [comment]
Should be corrected in version `4.6.2`

**Comment by nautonk** [comment]
Latest version works good. Thank you so much :)

**Comment by anassis** [comment]
I ahve found that it is more related to scrapping. In R Studio, I just uncheck "Use Internet Explorer library/proxy for HTTP" at Packages, under Options, and it seens solved the problem.
