### ISSUE TITLE
Quota limit?

### ISSUE THREAD

**Issue by Gerstep** [pat310/google-trends-api#18]
Whenever I try using trendData(); I get an error response from Google saying my quota limit is exceeded though it was just a few tries before. Any workaround?

**Comment by franklingu** [comment]
Basically you should not try querying too many times. Google may just ban you. Can try proxies

**Comment by pat310** [comment]
I've found that it also depends on how rapidly you make requests.  Even though `trendData()` can take an array of 'keywords', it may be better to send one word at a time at some interval.

Or yea try proxies as @franklingu suggested

**Comment by pasynkov** [comment]
I have `Error: Quota limit exceeded` but i dont query any times. no one query and quota limit? is it a bug may be?
