### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by chbighammsft** [pat310/google-trends-api#20]
Hi Patrick,

I've been searching your repo for a LICENSE file that describes the license that you released your project under. I can't find one, which implies that that the code is public, but not free to use. We'd like to use google-trends-api in a sample that we are working on, but we need to have an OSS license (MIT for preference) that we can show our legal team before we can use it.

Chuck Bigham
Microsoft Office

**Comment by pat310** [comment]
Hi Chuck,

I added the MIT license so the code is now free to use.

Thanks!
Patrick
