### ISSUE TITLE
Knowledge Sharing between packages

### ISSUE THREAD

**Issue by dreyco676** [pat310/google-trends-api#24]
Hey @pat310 I maintain the following Python implementation of Google Trends API. 

https://github.com/GeneralMills/pytrends

I really like what you've done with your JavaScript version. I just wanted to say that I will be keeping an eye on yours for new features to add to mine and that you should do the same!

In particular I've added `suggestions()` method that helps users refine their keyword searches by providing more detailed terms to use.

**Comment by pat310** [comment]
Thanks @dreyco676!  That's a good idea, I will definitely check it out.  I'll ping you whenever I add new features too.

**Comment by pat310** [comment]
@dreyco676 thanks for acknowledgement in the readme. I realized that I gave a shout out to your Python version in this quora a few months back:
https://www.quora.com/Does-Google-Trends-have-a-publicly-available-API

Looking forward to checking it out in more detail.

**Comment by dreyco676** [comment]
@pat310 Google's API has been updated and the one we were using before now is severely rate limited. Check out the new endpoints in requests.py. Feel free to ping me with any questions.

**Comment by Dayjo** [comment]
@dreyco676 - Have you managed to overcome the rate limiting at all? I had an idea that I'm going to attempt in a week or two based on this; https://github.com/pat310/google-trends-api/issues/36 but no idea if it could be a reliable solution.

**Comment by dreyco676** [comment]
Yea so the rate limit is mostly due to the depreciated API. If you use the new one its in the hundreds per min. I honestly haven't hit it.

**Comment by Dayjo** [comment]
Are you also doing auth stuff though and sending the cookies? I noticed your python version makes you authenticate. Unfortunately this module doesn't send any cookies or do any auth at the moment so the rate limit is very tight.

**Comment by dreyco676** [comment]
Yea we are logging into Google and then using that as a session which keeps
the cookies. Otherwise you hit the ratelimit pretty quick.

**Comment by Dayjo** [comment]
That's the key I think. The plan will be to add an auth layer to this. Will attempt to delve into the python to see how you're doing it :) Thanks

**Comment by dreyco676** [comment]
http://stackoverflow.com/questions/6754709/logging-in-to-google-using-python

might be better documented than my script

**Comment by Dayjo** [comment]
Yeah, thanks, I think the difficulty will be building it in a way that will work in generic Javascript and Node. Did you ever have any CORS issues?

**Comment by pat310** [comment]
@dreyco676 I think I got it working based on what you did in `requests.py`.  Thanks!!

@Dayjo I'm probably going to do a lot of refactoring - will likely switch to es6 class structure and use a bundler like webpack.

**Comment by Dayjo** [comment]
@pat310 sounds like a plan! Never used webpack personally, but I'm sure it's easy enough :)

**Comment by pat310** [comment]
@Dayjo I've only checked one of the end points, but it looks like CORS is not enabled, so the library will have to remain a node application :disappointed:.  I'll check some of the other endpoints to see if it would be possible to have any of the library work from the client

**Comment by Dayjo** [comment]
Ah damn, what's the difference between making a request from node, and making one from the browser? 

Did you make any progress on the auth/cookies side of things?

**Comment by pat310** [comment]
@Dayjo Just published v4. Let me know if you run into any problems.

@dreyco676 Thanks for the heads up on the endpoint.  I pointed out your library on the README.

**Comment by pat310** [comment]
closing this to clean up issues but definitely plan to continue knowledge sharing
