### ISSUE TITLE
Not getting how to have api functioning with 'require'

### ISSUE THREAD

**Issue by romulo-rocha** [pat310/google-trends-api#27]
I know this is an ignorance of mine and not an issue with the code. Firstly, I'd like to thank the author of this repository.

Could you explain how do I get this api functioning on my application? I know it all starts with: 

`var googleTrends = require('google-trends-api')`
But that's exactly where I am failing to succeed at using the plugin. :( Now I know it's dumb, lol but please have mercy on me.

I've downloaded requirejs from http://requirejs.org/ and included it on my page. But when I manage to require the plugin, it doesn't recognize "_module.exports_" or the "__dirname_" variable. I don't quite understand this require Javascript solution.

Thanks

**Comment by pat310** [comment]
@romulo-rocha 
I'll have to rewrite some things to add support for directly using the library in the browser (assuming there are no CORS issues).  For now, if you have a node back-end you should be able to require the library in there.  I'll keep this issue open until that is complete.

**Comment by romulo-rocha** [comment]
Thank you so much for your support!

Well, I am trying to use it on my web application which is not using a Node back-end (maybe that's the problem). I am working with Laravel framework (PHP) and AngularJS. If there's a way to use it in regular back-end services, I'd be very appreciated.

Take care!

**Comment by odovad** [comment]
This is a very similar issue. I am using a nodejs back-end. 
When I try to run the examples, it says me that "Promise" is required.
When I do "Promise = require('Promise');", it seems to be working but when running the example, I get the following error : 

TypeError: Object #<Object> has no method 'all'
    at Object.request [as trendData] (/lab/node_modules/google-trends-api/lib/utils/trendData.js:16:17)
    at repl:1:14
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
    at ReadStream.onData (readline.js:840:14)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:746:14)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
    at TTY.onread (net.js:526:21)

Can you help ?

Thank you very much in advance,

**Comment by Dayjo** [comment]
You might be able to get this working with something like `browserify` which allows you to require, and then compiles for web. However some of the modules used ('require-promise') may not work, and potentially would need to be switched out for an XHR library.

**Comment by pat310** [comment]
Thanks @Dayjo. I'm planning to change the package up to remove `request` and `request-promise` dependencies and also incorporate the ability to make that requests from the front-end

**Comment by lakshsyal123** [comment]
Hey i installed it by using `browserify` but its says 

`bundle.js:1 Uncaught Error: Cannot find module '/node_modules/google-trends-api/lib/utils/index.js'`

Well can anyone explain how can i resolve this error.

**Comment by garann** [comment]
I'm getting basically the same error as @lakshsyal123 and am also using Browserify via wzrd. The exact text is:
`Uncaught Error: Cannot find module '/node_modules/google-trends-api/lib/utils/'`

I went through and changed a few of the `require`s from e.g.
`require(__dirname + '/lib/utils/')`
to
`require('./lib/utils/')`
and that allowed execution to proceed to the next dependency.

**Comment by pat310** [comment]
I'll be adding a patch soon that will remove the node specific code so the library can be used in the browser.

**Comment by pat310** [comment]
Closed in PR #44
