### ISSUE TITLE
[Error: Quota limit exceeded, try again later]

### ISSUE THREAD

**Issue by sebfindling** [pat310/google-trends-api#31]
I guess I need an api key, but how do i set it, and let's consider google doesn't offer this API publicly

**Comment by pat310** [comment]
@sebfindling 
Yes this is an unofficial API so there is no api key and unfortunately, Google will limit the number of requests you can make in a given time period.  I have not figured out a way around this yet but when I do, I will reopen this issue.

**Comment by mattmoo** [comment]
Any idea of what the quota is?

**Comment by tjwudi** [comment]
Do we have an idea about what the limit is? Like 3000 requests per day maybe?
