### ISSUE TITLE
Category names

### ISSUE THREAD

**Issue by Dayjo** [pat310/google-trends-api#37]
Hello again,

I'm wondering about the category names, Is there a list of the exact values that are supported, or could we make it so that you can specify a category id (i.e. "Food & Drink" is category 71, and I wouldn't know how to supply this with the api, "food and drink", "food & drink", "food&drink" etc?.

On an aside, I'm also thinking, is it possible to supply the 'type' of search term? i.e. the difference between;

![image](https://cloud.githubusercontent.com/assets/1255512/19891432/0d0253aa-a038-11e6-88e2-ad7f66aed3b5.png)

and 

![image](https://cloud.githubusercontent.com/assets/1255512/19891443/15e392cc-a038-11e6-87a1-5353b4ffcf76.png)

Which seems to be separate to the 'category'.

**Comment by pat310** [comment]
@Dayjo Probably doesn't apply anymore since the api is so different 😭
