### ISSUE TITLE
Regions / Country breakdowns

### ISSUE THREAD

**Issue by Dayjo** [pat310/google-trends-api#38]
Hello again :)

I'm currently looking into how we might do requests using a specific region / city / county rather than the country. For instance, being able to do "England" or "Scotland" rather than limited to just "UK".

Not sure if anyone has managed to do this yet?

**Comment by pat310** [comment]
Is this the fix you reference in #40?

**Comment by Dayjo** [comment]
No, that's more about standardising the country codes (UK vs GB).

This one is more about regions, i.e. States in the US, or Countries in the UK (England, Scotland, Wales), or Counties.

**Comment by pat310** [comment]
@Dayjo For now just making users enter a country code.  See https://github.com/datasets/country-codes/blob/master/data/country-codes.csv

**Comment by Dayjo** [comment]
@pat310 cool, I shall look into the county / region specific stuff another time anyway :) 

Update looks good!
