### ISSUE TITLE
Problem with United Kingdom (UK / GB) Country Codes?

### ISSUE THREAD

**Issue by alexerhardt** [pat310/google-trends-api#40]
I've had issues with the abbreviations for the United Kingdom.

Both googleTrends.hotTrendsDetail("UK") and googleTrends.hotTrendsDetail("GB") were returning errors.

I checked the countryCodes file and it seems there is an inconsistency in denominations:

* mapToNumber uses UK
* mapToAbbreviation uses GB
* mapToDomain uses UK

I've had success changing everything to UK or to GB, but there needs to be consistency.

Perhaps ideally both codes should be accepted.

Would love to fix this myself but I'm not quite at that level of skill yet. If anyone needs a hot fix however, just know that you can get around it by tinkering the countryCodes file.

**Comment by Dayjo** [comment]
Heh, I actually fixed this in my local version. Hopefully will get a chance to find it again next week.

**Comment by pat310** [comment]
@alexerhardt Just made some big changes to the API so this issue probably doesn't apply anymore.  Users need to enter the [country code](https://github.com/datasets/country-codes/blob/master/data/country-codes.csv) now (no longer attempting to map names)
