### ISSUE TITLE
New Error  - 302 Moved / CAPTCHA

### ISSUE THREAD

**Issue by Dayjo** [pat310/google-trends-api#49]
Hello again!

Now, this was working a treat about an hour ago, but now I'm getting errors because google is no longer returning results, it's returning a 302 (if I log the raw output I get an html page, so the JSON is failing to parse and then the module is erroring - should check that it's valid json maybe?).

```html
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://ipv4.google.com/sorry/index?continue=https://www.google.com/trends/api/explore%3Fhl%3Den-US%26req%3D%257B%2522comparisonItem%2522%253A%255B%257B%2522keyword%2522%253A%2522Women%27s%2520march%2522%252C%2522hl%2522%253A%2522en-US%2522%252C%2522endTime%2522%253A%25222017-02-15T10%253A39%253A43.469Z%2522%252C%2522startTime%2522%253A%25222004-01-01T00%253A00%253A00.000Z%2522%252C%2522time%2522%253A%25222004-01-1%25202017-02-15%2522%257D%255D%252C%2522cat%2522%253A0%257D%26tz%3D300&amp;hl=en-US&amp;q=EgRSmJyrGO_fkMUFIhkA8aeDS4wL63ml_8QWbc51FLsxqzmXnxSDMgFj">here</A>.
</BODY></HTML>
```

This links over to a CAPTCHA like this;

![image](https://cloud.githubusercontent.com/assets/1255512/22970894/b01c5a32-f36b-11e6-9682-be1c6ff738e8.png)

Looks like we're going to have to implement the authentication and cookie sending afterall!

**Comment by pat310** [comment]
Ah, was hoping we wouldn't need to. Ok, thanks!

**Comment by pat310** [comment]
@Dayjo Do you know roughly how many requests you made before getting the captcha?

**Comment by Dayjo** [comment]
@pat310 I couldn't give you an exact number but it was only around 10. However, my workmate's screensaver is the google trends screensaver which doesn't auth, so even that got the CAPTCHA which was highly amusing. Not sure if that had done X number of requests that had pushed it over the limit or what.

**Comment by Dayjo** [comment]
@pat310 Can I help with the cookie / login implementation? I noticed your branch `49addcookie` but not sure where you've got to with it / what's next etc.

**Comment by Dayjo** [comment]
I think the best option to resolve this issue is simply to handle the error. 

If we can make it detect whether it's valid JSON and not throw a fatal error at least that way any script running this won't completely fail when it tries to decode the html. 

Happy to give this a go.

**Comment by pat310** [comment]
@Dayjo That's a good idea, just need to put a `try/catch` around `JSON.parse`

**Comment by Dayjo** [comment]
This is fixed by https://github.com/pat310/google-trends-api/pull/58 and the errors should be caught and made available in the `.catch()`
