### ISSUE TITLE
Having CORS issues with methods provided

### ISSUE THREAD

**Issue by dowdje** [pat310/google-trends-api#56]
I am testing your api locally in Reactjs. Since your methods don't require a header, I am unable to bypass the origin allowance issues. Is there a way to bypass CORS issues with this API?

**Comment by turnerniles** [comment]
You need to use the Node/Express back end to make the request. Google will not allow requests to be made from the browser / front end due to CORS restriction.

**Comment by pat310** [comment]
@turnerniles is right.  There may be a way to [bypass CORS](http://stackoverflow.com/questions/3076414/ways-to-circumvent-the-same-origin-policy) but they are kind of hacks so I wouldn't include it in this library.  I'll make it clear in the readme that there is a CORS restriction and this library is intended to be used from Node.  Thanks @dowdje!
