### ISSUE TITLE
relatedQueries/relatedTopics : Top and Rising

### ISSUE THREAD

**Issue by fredoh91** [pat310/google-trends-api#61]
thank you for your work and your for your package.

But I have question about the results of your relatedQueries() and relatedTopics() functions. I think they don't return the top and the rising status. 

Am i false ?

best regards

Fred

**Comment by Dayjo** [comment]
Hi @fredoh91,

Thanks for raising an issue, I'm not sure what your problem is though. Can you provide an example of how you're using the module and what it is, or is not returning?

**Comment by pat310** [comment]
@Dayjo @fredoh91 I think I'll close this for now unless there is still an issue?
