### ISSUE TITLE
SyntaxError: Unexpected token L

### ISSUE THREAD

**Issue by amakaa** [pat310/google-trends-api#62]
Started happening today all of a sudden.

**Comment by pat310** [comment]
@amakaa It seems to be working for me.  Can you give me some more detail?

**Comment by amakaa** [comment]
Sorry I solved the issue. I found I got kicked out for making too many
queries.

On Sun, Mar 26, 2017 at 10:28 PM, Patrick Trasborg <notifications@github.com

**Comment by Dayjo** [comment]
Yeah, this is the standard JSON fail error which should now be getting caught in the `.catch` of the calls. This happens when you hit the rate limit for your IP address. It's pretty annoying. I've found that if you make no more requests for 1 hour, you should be good to go.
