### ISSUE TITLE
Searching by category

### ISSUE THREAD

**Issue by MonsieurBaguette** [pat310/google-trends-api#67]
Hey There,

I was wondering if there's a way to choose the category, I see you specified it to 0 (cat: 0) in your code and changing it doesn't seem to affect the results.  

is there any way to make the category a parameter and make it work ? 

Thanks

**Comment by pat310** [comment]
Hi @monsieurbaguette I'm not even sure what cat does tbh haha... What would you expect it to do? Maybe there is a different parameter we can alter.

Category is mentioned [in this Python Google trends library](https://github.com/GeneralMills/pytrends/blob/master/README.md) but I'm not sure if it's of any help.

**Comment by MonsieurBaguette** [comment]
Yow @pat310 
disregard what I said , i found what i was looking for.
So i wanted to search for queries using a keyword and using CATEGORIES so when you make the request 
`  n = {
                    method: "GET",
                    host: "trends.google.com",
                    path: "/trends/api/explore",
                    qs: {
                        hl: t.hl,
                        req: JSON.stringify({
                            comparisonItem: c(t),
                            category: 44
                        }),
                        tz: 300
                    }` 

replacing cat with category and putting the id of the category instead of 0 (which means all categories) 
let's you search by category.
will map it later so i can make it a parameter in the methods.

**Comment by pat310** [comment]
Sounds good!
