### ISSUE TITLE
Error when comparison contains both Search terms and Topics

### ISSUE THREAD

**Issue by meetamit** [pat310/google-trends-api#75]
The error is "TypeError: Cannot read property 'requestOptions' of undefined"

This stems from the [handling of`the parsed results](https://github.com/pat310/google-trends-api/blob/0e76d45a2d111abc5bdde4e840247376cdaa06f5/src/utilities.js#L177).

The reason is because in Google's UI, and correspondingly in `widgets` JSON, there's a message at the top: "**Note:** This comparison contains both Search terms and Topics, which are measured differently." 

In JSON, it looks like this

```
[
  {
    "text": {
      "text": "This comparison contains both Search terms and Topics, which are measured differently"
    },
    "url": "https://support.google.com/trends/answer/4359550",
    "id": "topics_note",
    "type": "fe_text",
    "title": "",
    "template": "fe_explore_note",
    "embedTemplate": "fe_embed",
    "version": "1",
    "isLong": true,
    "isCurated": false
  },
  {
    "request": {
      "time": "2016-08-26 2017-08-26",
      "resolution": "WEEK",
      "locale": "en-US",
      "comparisonItem": [
        {
          "geo": {},
          "complexKeywordsRestriction": {
            "keyword": [
              {
                "type": "ENTITY",
                "value": "/m/0128447t"
              }
            ]
          }
        },
...
```

As a result, the rest of the widgets get shifted by 1, so `pos` needs to be incremented as well.

A possible fix is to modify [this `try` caluse](https://github.com/pat310/google-trends-api/blob/0e76d45a2d111abc5bdde4e840247376cdaa06f5/src/utilities.js#L99) of `parseResults()` to

    var widgets = JSON.parse(e.slice(4)).widgets;
    if (!widgets[0].request) { widgets.shift(); }
    return widgets;

**Comment by pat310** [comment]
Oh boy. What method/request are you making to get this error so I can replicate it?

**Comment by meetamit** [comment]
Search Term (Amazon Fire TV) vs Topic ('/m/0h65vcz')
 
```
    api.interestOverTime({ keyword: ['/m/0h65vcz', 'Amazon Fire TV'] }
```

**Comment by pat310** [comment]
@meetamit I made a PR in #76 to correct this issue if you want to check it out

**Comment by meetamit** [comment]
Thank you! I will check it out as soon as Google unblocks my IP address :( Yep, I managed to get myself blocked for making (not a crazy amount but still) too many concurrent queries to their API. I've since changed my code to throttle the requests, but the block still remains. In case you've been through this, I wonder whether you know how long the block takes to expire.
