### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Hujjat** [pat310/google-trends-api#86]
Hi. 

I am following the instructions in the readme file. but the examples are not working. 
For instance, 

`
googleTrends.autoComplete({keyword: 'Back to School'})
.then(function(results) {
  console.log(results);
})
.catch(function(err) {
  console.error(err);
})
`

Give the following error on console page. 

![capture](https://user-images.githubusercontent.com/5115878/32295180-b60e98d6-bf05-11e7-83ed-b336584df1a2.PNG)

Can anyone say what's wrong?

Thank's :)

**Comment by pat310** [comment]
Hello @Hujjat. It seems to be working for me:
```
{"default":{"topics":[{"mid":"/m/0414j6","title":"Back to School","type":"1986 film"},{"mid":"/m/068pw8","title":"Back to school","type":"Topic"},{"mid":"/m/05357_","title":"Tax holiday","type":"Holiday"},{"mid":"/m/04vwgn","title":"Fight Back to School","type":"1991 film"},{"mid":"/m/02pb6kt","title":"Fight Back to School II","type":"1992 film"}]}}
```

You are running this in node right? It won't work if you try to run it from the browser because of CORS

**Comment by Riedeman** [comment]
If you create a new Angular project (https://angular.io/guide/quickstart) and add the following lines to the app.component.ts file, you will get the CORS error above.  (You may also have to add "types": ["node"] into the src/tsconfig.app.json file too.)

Any way to set the "no-cors" mode on the request, or is a proxy server in order?

```
var googleTrends = require('google-trends-api');
googleTrends.autoComplete({ keyword: 'Back to School' }).then(function (results) { console.log(results); }).catch(function (err) { console.error(err); });
