### ISSUE TITLE
change server port 8080

### ISSUE THREAD

**Issue by wizidot** [pat310/google-trends-api#87]
Hi,
I would like to change the default port that is used by this script (8080). How can i achieve this ?
Thanks.

**Comment by pat310** [comment]
Hi @wizidot! Unfortunately I can't change the port that Google serves their trend data from if that's what you are referring to. Also, this library itself doesn't run on any particular port. Are you using this in a node express application?

**Comment by wizidot** [comment]
Hello,
No i would-like to use it in an hubot (slack) application. Thanks for your answer. I thought that the library use a specific server... I will look how to do it.
