### ISSUE TITLE
Not getting data for hourly trends.

### ISSUE THREAD

**Issue by edinhadzovic** [pat310/google-trends-api#89]
Hi,
I saw this api, and i love it but their is one problem in your example how to get data for every minute is not working for me. If i try i get only empties arrays and and objects.

Thx

**Comment by jtalen** [comment]
Did you set the `granularTimeResolution` to `true`? Maybe you can post your code?

**Comment by edinhadzovic** [comment]
omg.... that was it :+1:

**Comment by pat310** [comment]
Thanks @jtalen! @edinhadzovic do you remember which example it was so I can correct it?
