### ISSUE TITLE
Proxy Option for Requests

### ISSUE THREAD

**Issue by MWandtke** [pat310/google-trends-api#91]
Hey,

sometimes when you are behind a company proxy you will need the proxy option of request.
Is it possible, that you can provide this?

Thanks

**Comment by pat310** [comment]
hi @MWandtke yea I can provide that. There is a [PR open for proxy](https://github.com/pat310/google-trends-api/pull/80) right now. I was planning to change it so the user can select what proxy library they want to use to increase flexibility and remove the dependency. I'll circle back once that is done but if you need something right away, you should use what has been done in that branch.

**Comment by MWandtke** [comment]
nice. thanks man. sorry that I didn't see that PR

**Comment by pat310** [comment]
no worries 😃

**Comment by aaronmefford** [comment]
Just submitted a PR that will allow selecting a proxy library.

**Comment by pat310** [comment]
Thanks @aaronmefford! Going to cut a new version `4.5.0`

**Comment by ishtartec** [comment]
@pat310, the published version (`4.5.0`) in the npm repository is using and old `google-trends-api.js` in the lib directory that is not including the proxy changes. Proxying seems broken right now.

**Comment by pat310** [comment]
Thanks mate @ishtartec! Just a cut a new version (`4.6.0`) for some other changes. Should have a new file in the lib directory now.

**Comment by pat310** [comment]
👍 👍  closed in #95
