### ISSUE TITLE
Unexpected token L in JSON at position 0

### ISSUE THREAD

**Issue by mlegocki** [pat310/google-trends-api#97]
I know this issue has been resolved in the past but it seems it has resurfaced for me at least. This library was working a few weeks ago (@version 4.4.0) however now with the latest version I can't make any calls with the same code. It seems that Google is flagging these calls as 'automated' and unusual traffic. Any tips on getting past this? I'm signed into google and have tried this using both Chrome and Firefox. 

Using the latest version of node (9.6.1) and npm (5.6.0)

**SPECIFIC ERROR BELOW:**
{ SyntaxError: Unexpected token L in JSON at position 0
    at JSON.parse (<anonymous>)
    at a (/Users/MLegocki/FullStack/Projects/CryptoTrends/node_modules/google-trends-api/lib/google-trends-api.min.js:1:2976)
    at /Users/MLegocki/FullStack/Projects/CryptoTrends/node_modules/google-trends-api/lib/google-trends-api.min.js:1:3887
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  requestBody: '<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF="https://ipv4.google.com/sorry/index?continue=https://trends.google.com/trends/api/explore%3Fhl%3Den-US%26req%3D%257B%2522comparisonItem%2522%253A%255B%257B%2522keyword%2522%253A%2522Bitcoin%2522%252C%2522startTime%2522%253A%25222018-02-27T16%253A57%253A42.102Z%2522%252C%2522endTime%2522%253A%25222018-02-28T16%253A58%253A00.623Z%2522%252C%2522granularTimeResolution%2522%253Atrue%252C%2522hl%2522%253A%2522en-US%2522%252C%2522category%2522%253A0%252C%2522timezone%2522%253A300%252C%2522time%2522%253A%25222018-02-27T16%255C%255C%253A57%255C%255C%253A00%25202018-02-28T16%255C%255C%253A58%255C%255C%253A00%2522%257D%255D%252C%2522category%2522%253A0%252C%2522property%2522%253A%2522%2522%257D%26tz%3D300&amp;hl=en-US&amp;q=EgSSc1YEGJi_29QFIhkA8aeDS0BBalhU4gLJ-TA9tN-yDetFLzAyMgFy">here</A>.\r\n</BODY></HTML>\r\n' }

**Comment by pat310** [comment]
Thanks I'll check it out 🤔

**Comment by mlegocki** [comment]
It appears to be working again! The same code is now going through....weird that it was temporary. I'm on the same IP/network as well so I really don't have an explanation for why it wasn't working.

Thank you for looking into it! I'll keep you posted if it arises again.
